### ISSUE TITLE
Netlify Deploy Error: failed Building production JavaScript and CSS bundles 

### ISSUE THREAD

**Issue by stephenponce** [EllisMin/gatsby-blog-mdx#4]
Netlify deployment - script fails to build the production JS and CSS bundles (see below for error log details).

### **SUMMARY**
The error appears to be caused by the lack of capitalization on the shared directory which has the styles-global.js file (path: 'src/components/shared' ). 

In Netlify the directory is case-sensitive, but on Mac OS-X the directory is not case-sensitive, so the error does not appear on my local machine. 

### **HOW TO FIX**

**1. Rename the "shared" folder to "tmp"**
`git mv shared tmp`
- Note: If you have automated publishing enabled in Netlify then this will trigger a new build, which will fail again.
- So you may want to stop the build or disable automated builds in Netlify settings (before you do step 2).

**2. Push the re-named "tmp" folder to github.**
`git commit -m 'pt 1 - renaming shared to Shared...caps issue'`
`git push -u origin master`
- Note: you should validate the folder name changed from "shared" to "tmp" in github before step 3.

**3. Rename the "tmp" folder to "Shared"** 
`git mv tmp Shared`

**4. Push the update to github** 
`git commit -m 'pt2 - renaming shared to Shared...caps issue'
`git push -u origin master`
- Note: If you have automated publishing enabled in Netlify then this will trigger a new build, which should now succeed.
- If you previously disabled automated builds, then update the Netlify setting and redeploy.

### **ERROR LOG SNIPPET**
**Netlify Deploy Log Error** 
`
11:41:20 AM: info bootstrap finished - 7.509s
11:41:20 AM: ⠀
11:42:05 AM: failed Building production JavaScript and CSS bundles - 45.123s
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/MdxComponents/Collapsable'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/MdxComponents/TextBlock'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/Posts/PostCard'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/Posts/PostTemplate'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/Profile/ProfileImg'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../../Shared/styles-global' in '/opt/build/repo/src/components/Tags/Tag'
11:42:05 AM: Perhaps you need to install the package '../../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../Shared/styles-global' in '/opt/build/repo/src/components/Layout'
11:42:05 AM: Perhaps you need to install the package '../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../Shared/styles-global' in '/opt/build/repo/src/components/Loader'
11:42:05 AM: Perhaps you need to install the package '../Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../components/Shared/styles-global' in '/opt/build/repo/src/hooks'
11:42:05 AM: Perhaps you need to install the package '../components/Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed
11:42:05 AM: Can't resolve '../components/Shared/styles-global' in '/opt/build/repo/src/util'
11:42:05 AM: Perhaps you need to install the package '../components/Shared/styles-global'?
11:42:05 AM: error Generating JavaScript bundles failed

11:42:05 AM: /opt/build/repo/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/opt/build/repo/src/components/Layout/index.js f913bb9dcb465262c2927ecd3e43a27d
11:42:05 AM: Assigning to rvalue (5:0)
11:42:05 AM: | function getInitialTheme(){var savedTheme=__WEBPACK_MODULE_REFERENCE__23_64656661756c74__.getItem("theme");return savedTheme?JSON.parse(savedTheme):defaultTheme;}// Store theme in local storage
11:42:05 AM: | __WEBPACK_MODULE_REFERENCE__1_757365456666656374_call__(function(){__WEBPACK_MODULE_REFERENCE__23_64656661756c74__.setItem("theme",JSON.stringify(theme));},[theme]);// Save to theme global variable
11:42:05 AM: | !(function webpackMissingModule() { var e = new Error("Cannot find module '../components/Shared/styles-global'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()).curTheme=theme.mode;return _objectSpread(_objectSpread({},theme),{},{setTheme:function setTheme(_ref){var _setTheme2=_ref.setTheme,theme=_objectWithoutPropertiesLoose(_ref,["setTheme"]);return _setTheme(theme);}});}/* harmony default export */ var __WEBPACK_MODULE_DEFAULT_EXPORT__ = (UseTheme);
11:42:05 AM: not finished Generating image thumbnails - 47.323s
11:42:05 AM: not finished run queries - 45.387s
11:42:06 AM: ​
11:42:06 AM: ┌─────────────────────────────┐
11:42:06 AM: │   "build.command" failed    │
11:42:06 AM: └─────────────────────────────┘
11:42:06 AM: ​
11:42:06 AM:   Error message
11:42:06 AM:   Command failed with exit code 1: gatsby build`

**Comment by EllisMin** [comment]
@stephenponce 

Oops. I missed out on this one when I capitalized all the folders a while ago. I fixed it and verified that it deploys to Netlify without build failure.

I really appreciate that you spent time to submit this issue!

**Comment by stephenponce** [comment]
Glad I could help. Thanks for updating so quickly!
